<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="dev.viniduminsara.pahanaedu.business.bill.dto.BillDTO" %>
<%@ page import="dev.viniduminsara.pahanaedu.business.bill.dto.BillItemDTO" %>
<%@ page import="dev.viniduminsara.pahanaedu.business.customer.dto.CustomerDTO" %>
<%@ page import="dev.viniduminsara.pahanaedu.business.bill.dto.BillInvoiceDTO" %>
<%@ page import="dev.viniduminsara.pahanaedu.business.bill.dto.BillInvoiceItemDTO" %>

<%
    BillInvoiceDTO bill = (BillInvoiceDTO) request.getAttribute("bill");
    CustomerDTO customer = (CustomerDTO) request.getAttribute("customer");
%>

<html lang="en" data-theme="sunset">
<%@ include file="../partials/header.jsp" %>
<head>
    <style>
        @media print {
            #printButton {
                display: none;
            }
            #backButton {
                display: none;
            }
        }
    </style>
</head>
<body class="p-6">

<div class="flex justify-between px-8 py-4">
    <div>
        <a id="backButton" href="<%= request.getContextPath() %>/bill/create" class="btn btn-neutral">
            <i class="fa-solid fa-arrow-left"></i>Back
        </a>
    </div>
    <div>
        <button id="printButton" onclick="window.print()" class="btn btn-primary mr-2">
            <i class="fa-solid fa-print"></i> Print Invoice
        </button>
    </div>
</div>

<div class="bg-white max-w-3xl mx-auto rounded-xl p-8">

    <!-- Company Header -->
    <div class="flex items-center justify-between border-b pb-4 mb-6">
        <div class="flex items-center space-x-4">
            <i class="fa-solid fa-book text-4xl text-primary"></i>
            <div>
                <h1 class="text-2xl font-bold text-gray-800">Pahana Edu (Pvt) Ltd</h1>
                <p class="text-gray-600 text-sm">123 Main Street, Colombo, Sri Lanka</p>
                <p class="text-gray-600 text-sm">✉ info@pahanaedu.com</p>
            </div>
        </div>
    </div>

    <!-- Invoice Details -->
    <div class="mb-6 text-gray-600">
        <h2 class="text-xl font-semibold mb-2 text-gray-800">Invoice</h2>
        <p ><strong>Bill ID:</strong> <%= bill.getBillId() %></p>
        <p><strong>Customer:</strong> <%= customer.getName() %> (<%= customer.getEmail() %>)</p>
        <p><strong>Date:</strong> <%= new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()) %></p>
    </div>

    <!-- Items Table -->
    <div class="overflow-x-auto">
        <table class="table w-full border rounded">
            <thead class="bg-gray-200">
            <tr class="text-gray-700 border-">
                <th class="py-2">Item</th>
                <th class="py-2">Qty</th>
                <th class="py-2">Unit Price</th>
                <th class="py-2">Total</th>
            </tr>
            </thead>
            <tbody class="text-gray-600">
            <% for (BillInvoiceItemDTO item : bill.getBillItems()) { %>
                <tr>
                    <td><%= item.getItemName() %></td>
                    <td><%= item.getQuantity() %></td>
                    <td>Rs. <%= item.getUnitPrice() %></td>
                    <td>Rs. <%= item.getUnitPrice() * item.getQuantity() %></td>
                </tr>
            <% } %>
            </tbody>
        </table>
    </div>

    <!-- Total Section -->
    <div class="flex justify-end mt-6">
        <div class="text-right">
            <p class="text-xl font-bold text-gray-700">Total: Rs. <%= bill.getTotalAmount() %></p>
        </div>
    </div>

    <!-- Footer -->
    <div class="border-t mt-8 pt-4 text-center text-sm text-gray-500">
        <p>Thank you for your business!</p>
        <p>Invoice generated by Pahana Edu Billing System</p>
    </div>
</div>
</body>
</html>
